from datetime import datetime, timedelta
import requests
from .base import db
from sqlalchemy.dialects.postgresql import JSONB  # ← Добавь эту строку!

class FinancialReports(db.Model):
    __tablename__ = 'financial_reports'
    rrd_id = db.Column(db.BigInteger, primary_key=True)
    user_id = db.Column(db.BigInteger, nullable=False)
    realizationreport_id = db.Column(db.BigInteger)
    date_from = db.Column(db.TIMESTAMP(timezone=True))
    date_to = db.Column(db.TIMESTAMP(timezone=True))
    create_dt = db.Column(db.TIMESTAMP(timezone=True))
    currency_name = db.Column(db.Text)
    suppliercontract_code = db.Column(JSONB)
    gi_id = db.Column(db.BigInteger)
    dlv_prc = db.Column(db.Numeric)
    fix_tariff_date_from = db.Column(db.Date)
    fix_tariff_date_to = db.Column(db.Date)
    subject_name = db.Column(db.Text)
    nm_id = db.Column(db.BigInteger)
    brand_name = db.Column(db.Text)
    sa_name = db.Column(db.Text)
    ts_name = db.Column(db.Text)
    barcode = db.Column(db.Text)
    doc_type_name = db.Column(db.Text)
    quantity = db.Column(db.BigInteger)
    retail_price = db.Column(db.Numeric)
    retail_amount = db.Column(db.Numeric)
    sale_percent = db.Column(db.Integer)
    commission_percent = db.Column(db.Numeric)
    office_name = db.Column(db.Text)
    supplier_oper_name = db.Column(db.Text)
    order_dt = db.Column(db.TIMESTAMP(timezone=True))
    sale_dt = db.Column(db.TIMESTAMP(timezone=True))
    rr_dt = db.Column(db.TIMESTAMP(timezone=True))
    shk_id = db.Column(db.BigInteger)
    retail_price_withdisc_rub = db.Column(db.Numeric)
    delivery_amount = db.Column(db.Integer)
    return_amount = db.Column(db.Integer)
    delivery_rub = db.Column(db.Numeric)
    gi_box_type_name = db.Column(db.Text)
    product_discount_for_report = db.Column(db.Numeric)
    supplier_promo = db.Column(db.Numeric)
    rid = db.Column(db.BigInteger)
    ppvz_spp_prc = db.Column(db.Numeric)
    ppvz_kvw_prc_base = db.Column(db.Numeric)
    ppvz_kvw_prc = db.Column(db.Numeric)
    sup_rating_prc_up = db.Column(db.Numeric)
    is_kgvp_v2 = db.Column(db.Numeric)
    ppvz_sales_commission = db.Column(db.Numeric)
    ppvz_for_pay = db.Column(db.Numeric)
    ppvz_reward = db.Column(db.Numeric)
    acquiring_fee = db.Column(db.Numeric)
    acquiring_percent = db.Column(db.Numeric)
    payment_processing = db.Column(db.Text)
    acquiring_bank = db.Column(db.Text)
    ppvz_vw = db.Column(db.Numeric)
    ppvz_vw_nds = db.Column(db.Numeric)
    ppvz_office_name = db.Column(db.Text)
    ppvz_office_id = db.Column(db.BigInteger)
    ppvz_supplier_id = db.Column(db.BigInteger)
    ppvz_supplier_name = db.Column(db.Text)
    ppvz_inn = db.Column(db.Text)
    declaration_number = db.Column(db.Text)
    bonus_type_name = db.Column(db.Text)
    sticker_id = db.Column(db.Text)
    site_country = db.Column(db.Text)
    srv_dbs = db.Column(db.Boolean)
    penalty = db.Column(db.Numeric)
    additional_payment = db.Column(db.Numeric)
    rebill_logistic_cost = db.Column(db.Numeric)
    rebill_logistic_org = db.Column(db.Text)
    storage_fee = db.Column(db.Numeric, nullable=True)
    deduction = db.Column(db.Numeric, nullable=True)
    acceptance = db.Column(db.Numeric, nullable=True)
    assembly_id = db.Column(db.BigInteger)
    kiz = db.Column(db.Text)
    srid = db.Column(db.Text)
    report_type = db.Column(db.SmallInteger, nullable=True)
    is_legal_entity = db.Column(db.Boolean)
    trbx_id = db.Column(db.Text)
    installment_cofinancing_amount = db.Column(db.Numeric)
    wibes_wb_discount_percent = db.Column(db.Integer)
    cashback_amount = db.Column(db.Numeric, nullable=True)
    cashback_discount = db.Column(db.Numeric, nullable=True)
    cashback_commission_change = db.Column(db.Numeric, nullable=True)
    order_uid = db.Column(db.Text, nullable=True)

    def __init__(self, **kwargs):
        cleaned = {k: (None if v == 'null' else v) for k, v in kwargs.items()}
        for key, value in cleaned.items():
            setattr(self, key, value)